### ISSUE TITLE
Task List

### ISSUE THREAD

**Issue by nomotohiroki** [nomotohiroki/listpod-dj#4]
- [x] return no item rss when not authorized
- [ ] get upload videos from channel name
- [ ] search to rss
- [ ] create README
- [ ] create LICENSE text
- [x] to be able to use some functions without authorize

**Comment by nomotohiroki** [comment]
## Memo for README

based on perl app ListPod-App-Lite
dependent on python app youtube-dl
using Google Oauth2
